// data.js — auto-updated by update_prices.py
// Do not edit manually

window.PORTFOLIO_DATA = {

  watchlist: {
    updated: "9 Jun 2026, 02:19 PM",
    stocks: [
      { ticker: "ADANIPORTS", name: "Adani Ports", cmp: 1825.2 }
      { ticker: "ASTRAMICRO", name: "Astra Microwave", cmp: 1449.0 }
      { ticker: "GPIL", name: "Godawari Power & Ispat", cmp: 275.25 }
      { ticker: "PAYTM", name: "Paytm", cmp: 1065.5 }
      { ticker: "HBLENGINE", name: "HBL Engineering", cmp: 776.45 }
      { ticker: "KRISHNADEF", name: "Krishna Defence", cmp: 1235.3 }
      { ticker: "ZENTEC", name: "Zen Technologies", cmp: 1782.4 }
      { ticker: "MEDIASSIST", name: "Medi Assist", cmp: 348.45 }
      { ticker: "UNIMECH", name: "Unimech Aerospace", cmp: 1149.75 }
      { ticker: "GOLDCASE", name: "Goldcase", cmp: 23.86 }
      { ticker: "FEDFINA", name: "Federal Bank Fin. Services", cmp: 155.22 }
      { ticker: "EMMFORCE", name: "Emmforce Autotech", cmp: null }
      { ticker: "INTELLECT", name: "Intellect Design Arena", cmp: 737.15 }
      { ticker: "RATEGAIN", name: "RateGain Travel Tech", cmp: 753.35 }
      { ticker: "NSDL", name: "NSDL", cmp: 823.4 }
      { ticker: "NH", name: "Narayana Hrudayalaya", cmp: 1947.5 }
      { ticker: "BDL", name: "Bharat Dynamics", cmp: 1191.1 }
    ]
  },

  sectors: {
    updated: "9 Jun 2026",
    themes: [
      {
        name: "Defense, Aerospace & Shipbuilding",
        icon: "🛡️",
        summary: "Major structural shift this week: MoD ended BDL's monopoly on tactical missile production (June 7), opening 10–12 programs to private firms under DAP 2026. Adani Defence, Bharat Forge, ICOMM, and Solar Industries named as Development-cum-Production Partners. BDL retains role in a hybrid model. DRDO also launched an indigenous multi-fuel UAV engine program. Tata–ASML semiconductor MoU (May 16) benefits defense electronics long-term.",
        signals: [
          "🚨 BDL monopoly ends — tactical missiles open to Adani Defence, Bharat Forge, Solar Industries",
          "📋 DAP 2026 redistributes DRDO programs to private sector for faster timelines",
          "🚁 DRDO UAV engine: multi-fuel, stealth, modular architecture — indigenisation push",
          "⚠️ Watch: BEL/HAL in-house avionics expansion — vertical integration risk for sub-system cos"
        ]
      },
      {
        name: "Solar & Renewables",
        icon: "☀️",
        summary: "ALMM List-II mandate kicked in June 1: all grid-connected and open-access projects must now use MNRE-approved domestic modules AND cells. No blanket extension granted. Waaree, Premier Energies, and Emmvee shares up ~4% on the news. However, a supply side reality check — Indian module factories running at only ~25% capacity on average, pointing to demand-pull risk if project commissioning slows.",
        signals: [
          "✅ ALMM List-II live from June 1 — domestic cell mandate now enforceable",
          "📈 Waaree, Premier Energies, Emmvee: +4% on ALMM confirmation",
          "⚠️ Module factories at ~25% utilisation — oversupply risk if downstream demand gaps",
          "📅 Wafer mandate under ALMM follows June 2028 — next catalyst for upstream players"
        ]
      },
      {
        name: "AI & Data Centers",
        icon: "🤖",
        summary: "India's data center boom is real and accelerating. Microsoft opens Hyderabad region (3 availability zones) mid-2026, part of a $17.5B India commitment through 2029. Google building $15B facility in Andhra Pradesh; AWS committed $8.3B. Avendus projects 2 GW of active capacity by end of 2026, with $25B+ FDI flowing in. Indian beneficiaries: power cos (CESC, Tata Power), cooling infra, and domestic cloud players (Yotta, Sify).",
        signals: [
          "🏗️ Microsoft Hyderabad DC opens mid-2026 — 3 availability zones, $17.5B total India commitment",
          "💰 Google $15B Andhra Pradesh + AWS $8.3B — hyperscaler India capex accelerating",
          "⚡ 2 GW DC capacity projected by end 2026 — power sector tailwind intensifying",
          "🔍 Watch: Intellect Design Arena (AI fintech), RateGain (AI travel) — indirect beneficiaries"
        ]
      },
      {
        name: "Semiconductors",
        icon: "💾",
        summary: "Tata–ASML partnership formalised via MoU signed May 16 with PM present in Netherlands. Dholera fab (₹91,000 cr, 28nm) targeting first commercial chip production by late 2026. CG Power + Renesas Sanand plant (₹7,600 cr) to produce 15 million chips/day. India's semiconductor ecosystem is moving from announcements to construction phase — equipment orders and materials demand will start flowing in 2H 2026.",
        signals: [
          "🤝 Tata–ASML MoU signed May 16 — 28nm Dholera fab commercial production: late 2026",
          "🏭 CG Power + Renesas, Sanand: ₹7,600 cr, 15M chips/day — construction phase",
          "⚙️ Equipment and materials procurement wave beginning 2H 2026",
          "🔭 Watch: Agnit Semiconductors (GaN wafers, private) — AESA radar supply chain"
        ]
      },
      {
        name: "Power Transmission & Generation",
        icon: "⚡",
        summary: "POWERGRID floated 800 kV HVDC tender (April 2026) to evacuate 6 GW Rajasthan solar — the largest single HVDC line tender in India. Cabinet raised POWERGRID's equity investment threshold to ₹7,500 cr/subsidiary (from ₹5,000 cr) to accelerate 500 GW renewables target. Order flow strong: Hitachi Energy ₹647 cr (765 kV transformers), TARIL ₹53 cr HVDC converter order, GE Vernova 70+ transformers for RE corridors.",
        signals: [
          "📋 800 kV HVDC tender: 6 GW Rajasthan solar evacuation — India's largest HVDC line",
          "🏛️ Cabinet raises POWERGRID equity cap to ₹7,500 cr — accelerates 500 GW push",
          "💼 Hitachi Energy ₹647 cr + GE Vernova 70+ transformers — order cycle live",
          "📊 TARIL HVDC converter order — watch for Transformers & Rectifiers order intake momentum"
        ]
      }
    ]
  },

  ipos: {
    updated: "9 Jun 2026, 02:19 PM",
    listed: [
      { name: "Aegis Vopak Terminals Ltd",
        ticker: "AEGISVOPAK.NS",
        offerLow: 223,
        offerHigh: 235,
        listingDate: "02 Jun 2025",
        listingClose: null,
        cmp: 187.8,
        high52: 302.0,
        low52: 158.0,
        vsIpo: -18.0,
        business: "Operates liquid bulk storage terminals for petroleum products, chemicals, and LPG at key Indian ports; a JV between Aegis Logistics and Royal Vopak of Netherlands.",
        moat: "Terminal infrastructure at congested port locations is nearly impossible to replicate; long-term take-or-pay contracts with oil majors provide revenue visibility." },
      { name: "Schloss Bangalore Ltd (The Leela Hotels)",
        ticker: "SCHLOSS.NS",
        offerLow: 413,
        offerHigh: 435,
        listingDate: "02 Jun 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Owns and operates The Leela Palaces, Hotels and Resorts brand — ultra-luxury hospitality across key Indian gateway cities.",
        moat: "The Leela brand occupies a rare luxury segment in Indian hospitality; owned real estate in land-scarce city centres is a durable competitive advantage." },
      { name: "Prostarm Info Systems Ltd",
        ticker: "PROSTARM.NS",
        offerLow: 105,
        offerHigh: 105,
        listingDate: "03 Jun 2025",
        listingClose: null,
        cmp: 141.5,
        high52: 253.49,
        low52: 108.0,
        vsIpo: 34.8,
        business: "Provider of uninterruptible power supply (UPS) and power conditioning solutions for IT, telecom, and industrial clients.",
        moat: "Service network and government/PSU relationships built over decades provide recurring revenue and reference advantage in institutional sales." },
      { name: "Scoda Tubes Ltd",
        ticker: "SCODAT.NS",
        offerLow: 140,
        offerHigh: 140,
        listingDate: "04 Jun 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufacturer of high-precision stainless steel tubes and pipes used in pharmaceutical, dairy, food processing, and chemical industries.",
        moat: "Niche product quality certification (ASME, EN standards) creates a switching cost barrier with pharma and dairy customers who qualify suppliers infrequently." },
      { name: "Arisinfra Solutions Ltd",
        ticker: "ARISINFRA.NS",
        offerLow: 210,
        offerHigh: 222,
        listingDate: "25 Jun 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "B2B construction materials procurement platform connecting contractors and developers with suppliers of cement, steel, and other materials.",
        moat: "Aggregator network effects — as buyer volume grows, suppliers offer better pricing, creating a flywheel that is difficult for new entrants to replicate quickly." },
      { name: "Kalpataru Ltd",
        ticker: "KALPATARULD.NS",
        offerLow: 387,
        offerHigh: 414,
        listingDate: "01 Jul 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Real estate developer focused on premium residential projects in Mumbai Metropolitan Region and other major cities.",
        moat: "None identified — residential real estate is location-specific and competitive; brand premium is limited outside established micro-markets." },
      { name: "Ellenbarrie Industrial Gases Ltd",
        ticker: "ELLENBARRIE.NS",
        offerLow: 380,
        offerHigh: 400,
        listingDate: "01 Jul 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufactures and supplies industrial, medical, and specialty gases including oxygen, nitrogen, argon, and CO2 in Eastern India.",
        moat: "Cylinder and pipeline infrastructure is capital-intensive and regional; once large industrial customers install on-site gas plants from a supplier, switching costs are high." },
      { name: "Globe Civil Projects Ltd",
        ticker: "GLOBECIVIL.NS",
        offerLow: 68,
        offerHigh: 71,
        listingDate: "01 Jul 2025",
        listingClose: null,
        cmp: 40.55,
        high52: 95.0,
        low52: 33.5,
        vsIpo: -41.7,
        business: "Civil infrastructure EPC contractor executing roads, bridges, and water supply projects for government agencies primarily in North India.",
        moat: "None identified — infrastructure EPC is a highly competitive tendering business." },
      { name: "HDB Financial Services Ltd",
        ticker: "HDBFS.NS",
        offerLow: 700,
        offerHigh: 740,
        listingDate: "02 Jul 2025",
        listingClose: null,
        cmp: 624.65,
        high52: 889.5,
        low52: 555.3,
        vsIpo: -13.2,
        business: "HDFC Bank-promoted NBFC offering retail loans including personal, business, vehicle, and gold loans to underserved customer segments.",
        moat: "HDFC Bank parentage provides low-cost funding access and a ready cross-sell channel of over 80 million HDFC Bank customers — hard to replicate for standalone NBFCs." },
      { name: "Sambhv Steel Tubes Ltd",
        ticker: "SAMBHVSTEEL.NS",
        offerLow: 200,
        offerHigh: 211,
        listingDate: "02 Jul 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufacturer of steel tubes and pipes used in construction, infrastructure, and industrial applications.",
        moat: "None identified — steel tubes are a commoditised product with price-driven competition." },
      { name: "Indogulf Cropsciences Ltd",
        ticker: "INDOGULF.NS",
        offerLow: 105,
        offerHigh: 111,
        listingDate: "03 Jul 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufactures and markets pesticides, herbicides, and fungicides for Indian farmers, with a focus on branded formulation sales.",
        moat: "None identified — generic agrochemicals face intense price competition from large domestic and Chinese players." },
      { name: "Crizac Ltd",
        ticker: "CRIZAC.NS",
        offerLow: 233,
        offerHigh: 245,
        listingDate: "09 Jul 2025",
        listingClose: null,
        cmp: 212.0,
        high52: 375.59,
        low52: 173.35,
        vsIpo: -11.3,
        business: "Edtech and overseas education counselling company helping Indian students navigate university admissions in Canada, UK, and Australia.",
        moat: "Accredited university partnerships and student visa approval track records create a referral flywheel; however, moat is limited given low entry barriers." },
      { name: "Travel Food Services Ltd",
        ticker: "TRAVELFOOD.NS",
        offerLow: 1045,
        offerHigh: 1100,
        listingDate: "11 Jul 2025",
        listingClose: null,
        cmp: 1186.0,
        high52: 1445.0,
        low52: 1008.5,
        vsIpo: 10.6,
        business: "Operates food and beverage concessions in airports and highway rest stops under franchise brands including KFC, Burger King, and Subway.",
        moat: "Long-duration exclusive concession agreements with AAI and private airports create a captive, location-protected revenue stream." },
      { name: "Smartworks Coworking Spaces Ltd",
        ticker: "SMARTWORKS.NS",
        offerLow: 387,
        offerHigh: 407,
        listingDate: "17 Jul 2025",
        listingClose: 435.0,
        cmp: 446.15,
        high52: 619.0,
        low52: 361.5,
        vsIpo: 12.4,
        business: "Operates managed coworking and flexible office spaces for enterprise clients across major Indian metros.",
        moat: "None identified — coworking is a scale-but-competitive business; enterprise focus reduces churn but does not create durable pricing power." },
      { name: "Anthem Biosciences Ltd",
        ticker: "ANTHEMBIOSCIENCES.NS",
        offerLow: 540,
        offerHigh: 570,
        listingDate: "18 Jul 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Contract development and manufacturing organisation (CDMO) specialising in fermentation-based biologics and small molecules for global pharma companies.",
        moat: "Fermentation CDMO capacity is capital-intensive and requires specialised know-how; USFDA-inspected facility and EU-GMP certification create high barriers to entry." },
      { name: "GNG Electronics Ltd",
        ticker: "GNGELECTRONIC.NS",
        offerLow: 225,
        offerHigh: 237,
        listingDate: "30 Jul 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Distributor of refurbished laptops, desktops, and IT hardware procured from enterprise customers globally and resold in India.",
        moat: "None identified — electronics refurbishment distribution is a fragmented, low-barrier-to-entry business." },
      { name: "Indiqube Spaces Ltd",
        ticker: "INDIQUBE.NS",
        offerLow: 225,
        offerHigh: 237,
        listingDate: "30 Jul 2025",
        listingClose: null,
        cmp: 159.2,
        high52: 243.8,
        low52: 131.15,
        vsIpo: -31.1,
        business: "Commercial real estate developer and operator providing managed office campuses for large enterprises in Bengaluru and Pune.",
        moat: "Integrated campus ownership (own-and-operate model) with large enterprise tenants on long leases provides stable cash flows and occupancy certainty." },
      { name: "Brigade Hotel Ventures Ltd",
        ticker: "BRIGADEHVL.NS",
        offerLow: 85,
        offerHigh: 90,
        listingDate: "31 Jul 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Owns and operates mid-market and upscale hotels under Sheraton, Mercure, and Ibis brands in South India; hospitality arm of Brigade Group.",
        moat: "None identified — hotel operations at non-ultra-luxury tier face structural competition with limited brand differentiation." },
      { name: "Laxmi India Finance Ltd",
        ticker: "LAXMIIND.NS",
        offerLow: 150,
        offerHigh: 158,
        listingDate: "05 Aug 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Rajasthan-based NBFC providing secured business loans, gold loans, and vehicle finance to MSME and rural customers.",
        moat: "None identified — rural NBFC lending is competitive with microfinance, small finance banks, and larger NBFCs all competing for the same customer segment." },
      { name: "Aditya Infotech Ltd",
        ticker: "ADITYAINFO.NS",
        offerLow: 640,
        offerHigh: 675,
        listingDate: "05 Aug 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Distributor of CCTV and video surveillance equipment (primarily CP Plus brand) to installers and system integrators across India.",
        moat: "Exclusive national distribution rights for CP Plus give Aditya Infotech a near-monopoly position in the largest surveillance brand in India." },
      { name: "M&B Engineering Ltd",
        ticker: "MBENG.NS",
        offerLow: 370,
        offerHigh: 385,
        listingDate: "06 Aug 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufactures precision engineered components including valves, flanges, and pipe fittings for oil and gas, petrochemical, and power sectors.",
        moat: "ASME and API certifications plus customer-specific qualification approvals create switching costs with oil major customers; small order size makes re-qualification uneconomic." },
      { name: "National Securities Depository Ltd (NSDL)",
        ticker: "NSDL.BO",
        offerLow: 760,
        offerHigh: 800,
        listingDate: "06 Aug 2025",
        listingClose: 880.0,
        cmp: 823.4,
        high52: 1422.79,
        low52: 788.0,
        vsIpo: 5.6,
        business: "India's largest depository holding dematerialised securities accounts; processes settlement for NSE-listed instruments.",
        moat: "Duopoly with CDSL over India's depository infrastructure — regulations and network lock-in make new entry virtually impossible; NSDL handles ~78% of demat accounts by value." },
      { name: "Sri Lotus Developers & Realty Ltd",
        ticker: "SRILOTUS.NS",
        offerLow: 140,
        offerHigh: 150,
        listingDate: "06 Aug 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Residential and commercial real estate developer operating in mid-income housing segment in Mumbai and Thane markets.",
        moat: "None identified — mid-market residential real estate is location-specific with limited barriers to entry." },
      { name: "Highway Infrastructure Ltd",
        ticker: "HIGHWAYINFRA.NS",
        offerLow: 65,
        offerHigh: 70,
        listingDate: "12 Aug 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Civil infrastructure contractor building roads, bridges, and highway projects in Rajasthan and Madhya Pradesh.",
        moat: "None identified — road construction contracting is competitive and dependent on government spending cycles." },
      { name: "JSW Cement Ltd",
        ticker: "JSWCEMENT.NS",
        offerLow: 139,
        offerHigh: 147,
        listingDate: "14 Aug 2025",
        listingClose: null,
        cmp: 126.74,
        high52: 162.15,
        low52: 106.65,
        vsIpo: -11.4,
        business: "Manufactures and sells Portland and blended cement under the JSW Cement brand; part of the JSW Group conglomerate.",
        moat: "Captive steel slag from JSW Steel provides a low-cost raw material for slag cement, giving structural cost advantage over non-integrated peers." },
      { name: "All Time Plastics Ltd",
        ticker: "ALLTIMEPLASTIC.NS",
        offerLow: 255,
        offerHigh: 275,
        listingDate: "14 Aug 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufacturer and retailer of plastic organisers, storage solutions, and housewares sold through organised retail and e-commerce.",
        moat: "None identified — consumer plastics is a commoditised segment with low switching costs and abundant competition." },
      { name: "BlueStone Jewellery & Lifestyle Ltd",
        ticker: "BLUESTONE.NS",
        offerLow: 487,
        offerHigh: 517,
        listingDate: "19 Aug 2025",
        listingClose: null,
        cmp: 531.5,
        high52: 793.0,
        low52: 399.8,
        vsIpo: 5.9,
        business: "Online-first jewellery retailer selling certified diamond and gold jewellery with a try-at-home model and growing offline store presence.",
        moat: "Proprietary design IP and certified product assurance create a differentiated premium positioning in a market dominated by unbranded offline sellers." },
      { name: "Pace Digitek Ltd",
        ticker: "PACEDIGTECH.NS",
        offerLow: 142,
        offerHigh: 150,
        listingDate: "06 Oct 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Distributor of consumer electronics, smartphones, and IT accessories with last-mile delivery capabilities in Tier 2/3 cities.",
        moat: "None identified — electronics distribution is a low-margin, commoditised business." },
      { name: "Glottis Ltd",
        ticker: "GLOTTIS.NS",
        offerLow: 120,
        offerHigh: 127,
        listingDate: "07 Oct 2025",
        listingClose: null,
        cmp: 66.1,
        high52: 93.0,
        low52: 37.0,
        vsIpo: -46.5,
        business: "Manufacturer of medical consumables including laryngoscopes, endotracheal tubes, and airway management devices.",
        moat: "None identified — medical consumable manufacturing is competitive with several established domestic and multinational players." },
      { name: "Fabtech Technologies Ltd",
        ticker: "FABTECH.NS",
        offerLow: 84,
        offerHigh: 89,
        listingDate: "07 Oct 2025",
        listingClose: null,
        cmp: 144.9,
        high52: 262.8,
        low52: 132.7,
        vsIpo: 67.5,
        business: "Manufacturer of cleanroom furniture, modular panels, and pass-boxes for pharmaceutical manufacturing facilities in India.",
        moat: "Cleanroom validation and cGMP compliance expertise creates switching costs with pharma clients who face high recertification costs upon changing suppliers." },
      { name: "Om Freight Forwarders Ltd",
        ticker: "OMFRIEGHT.NS",
        offerLow: 128,
        offerHigh: 135,
        listingDate: "08 Oct 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Surface freight forwarding and logistics company handling full-truck-load and part-load shipments across India.",
        moat: "None identified — surface freight logistics is highly fragmented with low barriers to entry and intense price competition." },
      { name: "WeWork India Management Ltd",
        ticker: "WEWORK.NS",
        offerLow: 120,
        offerHigh: 126,
        listingDate: "10 Oct 2025",
        listingClose: null,
        cmp: 645.8,
        high52: 664.0,
        low52: 420.0,
        vsIpo: 425.0,
        business: "Flexible workspace operator running co-working centres for startups, freelancers, and enterprise teams across Indian metros.",
        moat: "None identified — co-working is a low-barrier business model with commoditised product and high customer churn." },
      { name: "Advance Agrolife Ltd",
        ticker: "ADVANCEAGRO.NS",
        offerLow: 90,
        offerHigh: 100,
        listingDate: "13 Oct 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Agrochemical company manufacturing and marketing insecticides, herbicides, and fungicides for the Indian crop protection market.",
        moat: "None identified — generic agrochemical formulation is commoditised; competitive advantage primarily depends on field sales reach." },
      { name: "Tata Capital Ltd",
        ticker: "TATACAP.NS",
        offerLow: 310,
        offerHigh: 326,
        listingDate: "13 Oct 2025",
        listingClose: 330.0,
        cmp: 318.95,
        high52: 367.3,
        low52: 296.0,
        vsIpo: 0.3,
        business: "Tata Group's diversified financial services NBFC providing retail, commercial, and housing loans along with wealth management services.",
        moat: "Tata brand provides a trust premium and lower funding cost; parent group captive business from Tata employees and customers reduces customer acquisition costs." },
      { name: "LG Electronics India Ltd",
        ticker: "LGEINDIA.NS",
        offerLow: 1080,
        offerHigh: 1140,
        listingDate: "14 Oct 2025",
        listingClose: 1682.8,
        cmp: 1537.6,
        high52: 1749.0,
        low52: 1304.1,
        vsIpo: 38.5,
        business: "Indian subsidiary of South Korea's LG Electronics; manufactures and markets home appliances, TVs, and mobile products in India.",
        moat: "Brand recognition and after-sales service network spanning 3,000+ towns — combined with Korean parent's R&D pipeline — creates durable consumer preference in premium appliance tiers." },
      { name: "Canara Robeco Asset Management Co. Ltd",
        ticker: "CRAMC.NS",
        offerLow: 253,
        offerHigh: 266,
        listingDate: "16 Oct 2025",
        listingClose: 280.25,
        cmp: 243.54,
        high52: 351.65,
        low52: 214.2,
        vsIpo: -6.2,
        business: "Asset management company operating mutual funds under the Canara Robeco brand, a joint venture between Canara Bank and Robeco Group.",
        moat: "AMC industry has inherent operating leverage — AUM growth amplifies margins without proportional cost growth; regulatory entry barriers create oligopoly-like returns for established players." },
      { name: "Rubicon Research Ltd",
        ticker: "RUBICON.NS",
        offerLow: 461,
        offerHigh: 485,
        listingDate: "16 Oct 2025",
        listingClose: 620.1,
        cmp: 1166.0,
        high52: 1370.0,
        low52: 570.75,
        vsIpo: 146.5,
        business: "Specialty pharmaceutical company developing and marketing patented orally disintegrating tablets (ODT) and sustained-release formulations globally.",
        moat: "Proprietary ODT technology platform (ODTRx) with 75+ patents and FDA 505(b)(2) regulatory pathway creates defensible IP moat in niche dosage forms." },
      { name: "Canara HSBC Life Insurance Co. Ltd",
        ticker: "CANHLIFE.NS",
        offerLow: 100,
        offerHigh: 106,
        listingDate: "17 Oct 2025",
        listingClose: 106.0,
        cmp: 140.64,
        high52: 159.0,
        low52: 106.0,
        vsIpo: 36.5,
        business: "Life insurance company operating as a joint venture among Canara Bank, Punjab National Bank, and HSBC Insurance; distributes through bank branches.",
        moat: "Bank-assurance model with exclusive distribution through Canara Bank's 10,000+ branches provides low-cost customer acquisition that pure-play insurers cannot replicate." },
      { name: "Lenskart Solutions Ltd",
        ticker: "LENSKART.NS",
        offerLow: 382,
        offerHigh: 402,
        listingDate: "10 Nov 2025",
        listingClose: null,
        cmp: 501.35,
        high52: 557.65,
        low52: 356.1,
        vsIpo: 27.9,
        business: "Omnichannel eyewear retailer operating the Lenskart brand with online and 2,000+ offline stores, proprietary frames, and in-house optical labs.",
        moat: "Vertical integration from design to retail combined with a large proprietary optical lab network allows faster delivery and 40-50% cost advantage over traditional eyewear chains." },
      { name: "Billionbrains Garage Ventures Ltd (Groww)",
        ticker: "GROWW.NS",
        offerLow: 95,
        offerHigh: 100,
        listingDate: "12 Nov 2025",
        listingClose: null,
        cmp: 194.18,
        high52: 227.2,
        low52: 112.0,
        vsIpo: 99.2,
        business: "Operates Groww, India's largest retail investment platform by number of demat accounts, offering stocks, mutual funds, and digital gold.",
        moat: "Network effects from India's largest retail investor base (100M+ users) combined with a simplified UX and zero-cost model create strong user retention and cross-sell potential." },
      { name: "Pine Labs Ltd",
        ticker: "PINELABS.NS",
        offerLow: 210,
        offerHigh: 221,
        listingDate: "14 Nov 2025",
        listingClose: null,
        cmp: 149.09,
        high52: 284.0,
        low52: 134.73,
        vsIpo: -30.8,
        business: "Fintech company providing point-of-sale payment solutions, EMI financing, and merchant analytics to offline and online retailers globally.",
        moat: "Deeply embedded POS terminals with proprietary software in major retail chains create high switching costs; EMI-at-POS product is differentiated from pure-play payment processors." },
      { name: "PhysicsWallah Ltd",
        ticker: "PWL.NS",
        offerLow: 103,
        offerHigh: 109,
        listingDate: "18 Nov 2025",
        listingClose: 145.0,
        cmp: 105.54,
        high52: 161.99,
        low52: 77.72,
        vsIpo: -0.4,
        business: "EdTech company offering affordable live and recorded coaching for JEE, NEET, and other competitive entrance exams through the PW platform.",
        moat: "Low-price positioning combined with highest-rated faculty content has built a massive user base; pricing discipline keeps out premium competitors in the mass segment." },
      { name: "Emmvee Photovoltaic Power Ltd",
        ticker: "EMMVEE.NS",
        offerLow: 217,
        offerHigh: 217,
        listingDate: "18 Nov 2025",
        listingClose: null,
        cmp: 335.35,
        high52: 343.5,
        low52: 171.51,
        vsIpo: 54.5,
        business: "Manufactures solar PV modules and develops rooftop and ground-mounted solar power systems for commercial and industrial clients.",
        moat: "None identified — solar module manufacturing is a competitive commodity business with Chinese players dominating global pricing." },
      { name: "Tenneco Clean Air India Ltd",
        ticker: "TENNECO.NS",
        offerLow: 378,
        offerHigh: 397,
        listingDate: "19 Nov 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufactures emission control products (catalytic converters, DPF systems) for passenger vehicles and commercial vehicles sold to OEMs in India.",
        moat: "Sole-source supply agreements with major OEMs for vehicle-specific emission control components create sticky revenues; BS6 compliance requirements ensure continued demand growth." },
      { name: "Fujiyama Power Systems Ltd",
        ticker: "FUJIYAMA.NS",
        offerLow: 216,
        offerHigh: 228,
        listingDate: "20 Nov 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufactures diesel generator sets, power control panels, and silent enclosures for backup power applications in industrial and commercial segments.",
        moat: "None identified — DG set manufacturing is competitive with Cummins, Kirloskar, and Greaves providing stronger brand alternatives." },
      { name: "Capillary Technologies India Ltd",
        ticker: "CAPILLARYTEC.NS",
        offerLow: 549,
        offerHigh: 577,
        listingDate: "21 Nov 2025",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "SaaS platform providing loyalty and customer engagement solutions to large retailers, QSRs, and CPG brands in emerging markets.",
        moat: "Loyalty platform stickiness comes from deep integration with POS, CRM, and e-commerce stacks — ripping out the platform requires multi-quarter migration with high operational risk for retailers." },
      { name: "Excelsoft Technologies Ltd",
        ticker: "EXCELSOFT.NS",
        offerLow: 114,
        offerHigh: 120,
        listingDate: "26 Nov 2025",
        listingClose: null,
        cmp: 83.0,
        high52: 142.59,
        low52: 66.4,
        vsIpo: -29.1,
        business: "Provides digital learning content, LMS platforms, and assessment tools for corporate training and K-12/higher education institutions globally.",
        moat: "Long-term content licensing agreements with global publishers and accredited assessment banks create customer stickiness; migrating content libraries is expensive and disruptive." },
      { name: "Sudeep Pharma Ltd",
        ticker: "SUDEEPPHARMA.NS",
        offerLow: 563,
        offerHigh: 593,
        listingDate: "28 Nov 2025",
        listingClose: 730.0,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Specialised API (active pharmaceutical ingredient) manufacturer supplying non-steroidal anti-inflammatory drugs and analgesic intermediates globally.",
        moat: "DMF-filed APIs in regulated markets (USFDA, EU) with deep chemistry expertise in specific molecule families create switching costs with pharma customers dependent on supply consistency." },
      { name: "Meesho Ltd",
        ticker: "MEESHO.NS",
        offerLow: 105,
        offerHigh: 111,
        listingDate: "10 Dec 2025",
        listingClose: null,
        cmp: 164.31,
        high52: 254.4,
        low52: 125.56,
        vsIpo: 52.1,
        business: "Social commerce and value e-commerce platform connecting consumers with SME sellers; India's largest horizontal e-commerce platform by order volume.",
        moat: "Seller supply network of 1.5M+ SME merchants and logistics infrastructure built for small, low-value orders create economies of scale moats in India's Tier 3/4 cities." },
      { name: "ICICI Prudential Asset Management Co. Ltd",
        ticker: "ICICIAMC.NS",
        offerLow: 2050,
        offerHigh: 2165,
        listingDate: "19 Dec 2025",
        listingClose: null,
        cmp: 3250.0,
        high52: 3611.0,
        low52: 2516.71,
        vsIpo: 54.2,
        business: "India's second largest AMC by AUM, managing mutual funds, PMS, and AIF products under the ICICI Prudential brand.",
        moat: "Top-3 AMC with ₹9L+ crore AUM; regulatory entry barriers and brand trust create a durable flywheel — distribution is high-fixed-cost and existing brands dominate shelf space." },
      { name: "Bharat Coking Coal Ltd",
        ticker: "BHARATCOAL.NS",
        offerLow: 21,
        offerHigh: 23,
        listingDate: "19 Jan 2026",
        listingClose: 40.28,
        cmp: 40.27,
        high52: 45.09,
        low52: 29.74,
        vsIpo: 83.0,
        business: "Coal India subsidiary and India's largest coking coal producer supplying steel makers with washed and raw coking coal from Jharkhand mines.",
        moat: "Monopoly position in India's coking coal production — domestic steel makers have no viable alternative supplier for captive coking coal; government ownership provides policy protection." },
      { name: "Amagi Media Labs Ltd",
        ticker: "AMAGI.NS",
        offerLow: 343,
        offerHigh: 361,
        listingDate: "21 Jan 2026",
        listingClose: null,
        cmp: 404.9,
        high52: 450.8,
        low52: 310.2,
        vsIpo: 15.0,
        business: "SaaS platform for cloud-based TV channel creation, distribution, and monetisation used by media companies and streaming platforms globally.",
        moat: "End-to-end cloud broadcasting stack with integrations across 150+ distribution platforms — migrating a live TV channel off the platform requires significant downtime and technical risk." },
      { name: "Shadowfax Technologies Ltd",
        ticker: "SHADOWFAX.NS",
        offerLow: 118,
        offerHigh: 124,
        listingDate: "28 Jan 2026",
        listingClose: null,
        cmp: 214.66,
        high52: 217.1,
        low52: 98.55,
        vsIpo: 77.4,
        business: "Last-mile and express logistics platform aggregating a gig-delivery workforce for e-commerce, quick commerce, and D2C brands.",
        moat: "None identified — logistics aggregation is highly competitive with Delhivery, Ecom Express, and Xpressbees providing similar services." },
      { name: "Fractal Analytics Ltd",
        ticker: "FRACTAL.NS",
        offerLow: 857,
        offerHigh: 900,
        listingDate: "16 Feb 2026",
        listingClose: null,
        cmp: 960.6,
        high52: 1118.0,
        low52: 733.7,
        vsIpo: 9.3,
        business: "AI and advanced analytics consulting company serving Fortune 500 clients in BFSI, CPG, healthcare, and technology globally.",
        moat: "Proprietary AI platforms (Cortex, etc.) and a large data science talent pool create delivery differentiation; established client relationships in BFSI with multi-year contracts provide revenue stability." },
      { name: "Aye Finance Ltd",
        ticker: "AYEF.NS",
        offerLow: 123,
        offerHigh: 129,
        listingDate: "16 Feb 2026",
        listingClose: 129.0,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "NBFC providing secured and unsecured working capital loans to micro-enterprises and informal businesses in Tier 2/3 cities.",
        moat: "Proprietary cluster-based underwriting model leverages industry and peer data rather than credit bureau scores — enables profitable lending in a segment most formal lenders avoid." },
      { name: "Gaudium IVF & Women Health Ltd",
        ticker: "GAUDIUMIVF.NS",
        offerLow: 75,
        offerHigh: 79,
        listingDate: "27 Feb 2026",
        listingClose: null,
        cmp: 105.76,
        high52: 133.0,
        low52: 69.18,
        vsIpo: 37.4,
        business: "Fertility treatment and women's health chain operating IVF centres and gynaecology clinics across India.",
        moat: "Embryologist expertise and lab quality certification are scarce and sticky — high-quality IVF labs command pricing power in a market driven by success rates, not price." },
      { name: "Shree Ram Twistex Ltd",
        ticker: "SRTL.NS",
        offerLow: 95,
        offerHigh: 100,
        listingDate: "28 Feb 2026",
        listingClose: null,
        cmp: 41.75,
        high52: 73.36,
        low52: 40.0,
        vsIpo: -57.2,
        business: "Manufacturer of twisted yarns, threads, and texturised polyester yarn for domestic textile and apparel companies.",
        moat: "None identified — yarn manufacturing is a commodity business with minimal differentiation." },
      { name: "Clean Max Enviro Energy Solutions Ltd",
        ticker: "CLEANMAX.NS",
        offerLow: 1000,
        offerHigh: 1053,
        listingDate: "02 Mar 2026",
        listingClose: null,
        cmp: 1197.9,
        high52: 1398.6,
        low52: 727.1,
        vsIpo: 16.7,
        business: "Develops, owns, and operates captive renewable energy (solar and wind) projects for large industrial and commercial customers under long-term PPAs.",
        moat: "Long-term power purchase agreements (10-25 years) with C&I customers provide locked-in cash flows; site-specific permitting and land acquisition create barriers to replicating assets." },
      { name: "PNGS Reva Diamond Jewellery Ltd",
        ticker: "PNGSREVA.NS",
        offerLow: 195,
        offerHigh: 205,
        listingDate: "04 Mar 2026",
        listingClose: null,
        cmp: 388.8,
        high52: 476.75,
        low52: 324.25,
        vsIpo: 94.4,
        business: "Diamond and gold jewellery retailer operating branded stores and wholesale supply in Maharashtra.",
        moat: "None identified — branded jewellery retail has moderate switching costs but the sector is highly competitive with Tanishq, Malabar, and regional players." },
      { name: "Omnitech Engineering Ltd",
        ticker: "OMNITECH.NS",
        offerLow: 124,
        offerHigh: 131,
        listingDate: "05 Mar 2026",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Engineering company manufacturing and supplying precision steel fabricated structures and components for the power and infrastructure sectors.",
        moat: "None identified — steel fabrication contracting is competitive with cost as the primary differentiator." },
      { name: "SEDEMAC Mechatronics Ltd",
        ticker: "SEDEMAC.NS",
        offerLow: 1287,
        offerHigh: 1352,
        listingDate: "11 Mar 2026",
        listingClose: null,
        cmp: 2607.5,
        high52: 2649.3,
        low52: 1413.1,
        vsIpo: 97.6,
        business: "Designs and manufactures mechatronic control systems (engine management, start-stop, transmission control) for two-wheelers and three-wheelers.",
        moat: "Deep embedded software and hardware integration with OEM drivetrains — once Sedemac systems are designed-in, the switching cost for OEMs is an entire vehicle platform re-engineering cycle." },
      { name: "Rajputana Stainless Ltd",
        ticker: "RJPS.NS",
        offerLow: 116,
        offerHigh: 122,
        listingDate: "19 Mar 2026",
        listingClose: 123.95,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufacturer of stainless steel sheets, coils, and strips used in kitchen equipment, railways, and industrial applications.",
        moat: "None identified — stainless steel flat products face intense competition from large integrated mills." },
      { name: "Innovision Ltd",
        ticker: "INNOVISION.NS",
        offerLow: 494,
        offerHigh: 519,
        listingDate: "23 Mar 2026",
        listingClose: 466.0,
        cmp: 293.5,
        high52: 470.0,
        low52: 284.0,
        vsIpo: -42.1,
        business: "IT and digital transformation services company providing ERP implementation, cloud migration, and managed services to mid-market enterprises.",
        moat: "None identified — IT services for mid-market is highly competitive with many regional and global players." },
      { name: "GSP Crop Science Ltd",
        ticker: "GSPCROPSC.NS",
        offerLow: 304,
        offerHigh: 320,
        listingDate: "25 Mar 2026",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufactures and markets branded pesticides, herbicides, and fungicides for Indian farmers through a dealer network.",
        moat: "None identified — generic agrochemical formulation faces intense competition from large domestic players and Chinese imports." },
      { name: "Central Mine Planning & Design Institute Ltd (CMPDI)",
        ticker: "CMPDI.NS",
        offerLow: 290,
        offerHigh: 305,
        listingDate: "30 Mar 2026",
        listingClose: null,
        cmp: 245.04,
        high52: 263.65,
        low52: 150.16,
        vsIpo: -17.6,
        business: "Coal India subsidiary providing mine planning, geological survey, and technical consultancy services for coal and mineral mining projects in India.",
        moat: "Monopoly position in Indian coal mine planning consultancy backed by 50+ years of proprietary geological data — government mandate gives structural revenue security." },
      { name: "Amir Chand Jagdish Kumar (Exports) Ltd",
        ticker: "AMIRCHAND.NS",
        offerLow: 201,
        offerHigh: 212,
        listingDate: "02 Apr 2026",
        listingClose: null,
        cmp: 122.5,
        high52: 200.0,
        low52: 117.02,
        vsIpo: -40.7,
        business: "Integrated basmati rice processor and exporter supplying premium basmati varieties to Middle East, Europe, and North America.",
        moat: "None identified — basmati rice export is competitive with KRBL, LT Foods, and many smaller exporters competing on price and grade." },
      { name: "Powerica Ltd",
        ticker: "POWERICA.NS",
        offerLow: 375,
        offerHigh: 395,
        listingDate: "02 Apr 2026",
        listingClose: 366.0,
        cmp: 485.1,
        high52: 586.3,
        low52: 365.1,
        vsIpo: 26.0,
        business: "Manufactures and rents diesel and gas generator sets for construction sites, events, and industrial backup power applications.",
        moat: "None identified — generator rental is a services business with low barriers to entry and primarily price-driven competition." },
      { name: "Sai Parenteral's Ltd",
        ticker: "SAIPAREN.NS",
        offerLow: 372,
        offerHigh: 392,
        listingDate: "02 Apr 2026",
        listingClose: 400.0,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufactures sterile injectable pharmaceuticals (IV bags, vials, ampoules) for domestic and international hospitals and pharma companies.",
        moat: "Sterile injectable manufacturing requires WHO-GMP facility compliance — certification is expensive and time-consuming, creating a meaningful barrier versus non-sterile manufacturers." },
      { name: "Om Power Transmission Ltd",
        ticker: "OMPOWER.NS",
        offerLow: 166,
        offerHigh: 175,
        listingDate: "17 Apr 2026",
        listingClose: 186.0,
        cmp: 180.83,
        high52: 206.0,
        low52: 167.0,
        vsIpo: 6.1,
        business: "Manufactures power transmission hardware including earthing materials, cable trays, and earthing electrodes for utilities and EPC contractors.",
        moat: "None identified — power hardware manufacturing is competitive with many domestic players serving price-sensitive utility buyers." },
      { name: "OnEMI Technology Solutions Ltd",
        ticker: "ONEMI.NS",
        offerLow: 162,
        offerHigh: 171,
        listingDate: "08 May 2026",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Fintech platform providing embedded EMI financing and BNPL solutions through a bank-agnostic infrastructure to retailers and consumers.",
        moat: "Bank-agnostic API infrastructure enabling any bank to offer EMI at checkout creates network effects as more issuers join — switching costs rise as each bank customises their offering." }
    ],
    upcoming: [
      { name: "CMR Green Technologies Ltd",
        ticker: "CMRGREEN.NS",
        offerLow: 182,
        offerHigh: 192,
        listingDate: "10 Jun 2026",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Aluminium recycling company processing post-consumer and industrial scrap into secondary aluminium alloys for the automotive and consumer durables industries.",
        moat: "Proximity to scrap sourcing clusters and long-term supply agreements with OEMs reduce raw material cost volatility; secondary aluminium has a structural cost advantage over primary smelting." },
      { name: "Hexagon Nutrition Ltd",
        ticker: "HEXANUT.NS",
        offerLow: 42,
        offerHigh: 45,
        listingDate: "12 Jun 2026",
        listingClose: null,
        cmp: null,
        high52: null,
        low52: null,
        vsIpo: null,
        business: "Manufactures and markets fortified food and nutritional supplement products including micronutrient premixes, ORS, and health beverages for domestic and export markets.",
        moat: "None identified — nutritional supplements and food fortification is a competitive market with large FMCG players." }
    ]
  }

};
